baseURL = 'https://buffguycodes.com/'
languageCode = 'en-us'
title = 'Buff Guy Codes'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "Links"
    name = "Links"
    url = "/links"
    weight = 3

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 4